# 4.1 Aufgaben

Diese Aufgabe ist länger als Lernzielkontrolle und fasst alle Themen aus 4.1 and früher zusammen.

1. Bitte verbessern Sie die folgenden Funktionen mit NumPy ohne numpy.cov(). 
2. Messen Sie, welche Funktion schneller ist: kov_mat(), np_kov_mat() oder numpy.cov().
3. Die Zufallsvariablen sind auf der Grundgesamtheit und keine Stichprobe.

> Bitte benutzen Sie NumPy.


In [1]:
def kov(x, y):
    Ex = sum(x) / len(x)
    Ey = sum(y) / len(y)

    xy = [x * y for x, y in zip(x,y)] # Liste-Comprehension

    Exy = sum(xy) / len(xy)

    return round(Exy - (Ex * Ey), 2)

In [2]:
def kov_mat(*args):
    # Liste-Comprehension um einzigarg Liste zu erzeugen
    # [0] * 2 ist zweimal die gleiche Liste
    temp = [ [ 0 for _ in range(0,len(args)) ] for _ in range(0, len(args))]
    
    for i in range(0,len(args)):

        for j in range(0,len(args)):
            # print(f'Index: ({i}, {j})')
            temp[i][j] = kov(args[i], args[j])

    # for row in temp:
    #   print(row)

    return temp

In [3]:
import numpy as np

In [4]:
def np_kov(x, y):

    x, y = np.array(x), np.array(y)
    Ex, Ey = np.mean(x), np.mean(y)

    Exy = np.mean(x * y)

    return np.round(Exy - (Ex * Ey), 4)

In [5]:
np_kov([1,1,3], [0,2,2])

np.float64(0.4444)

In [6]:
kov([1,1,3], [0,2,2])

0.44

In [7]:
def np_kov_mat(*args):
    # Liste-Comprehension um einzigarg Liste zu erzeugen
    # [0] * 2 ist zweimal die gleiche Liste
    # temp = [ [ 0 for _ in range(0,len(args)) ] for _ in range(0, len(args))]
    lang = len(args)
    temp = np.ndarray((lang, lang))

    for i in range(0,lang):

        for j in range(0,lang):
            # print(f'Index: ({i}, {j})')
            temp[i][j] = np_kov(args[i], args[j])

    # for row in temp:
    #     print(row)

    return temp

In [8]:
np.var([1,1,3])

np.float64(0.888888888888889)

In [9]:
np_kov_mat([1,1,3], [0,2,2])

array([[0.8889, 0.4444],
       [0.4444, 0.8889]])

In [10]:
kov_mat([1,1,3], [0,2,2])

[[0.89, 0.44], [0.44, 0.89]]

In [11]:
%%timeit -n 10000
kov([1,1,3], [0,2,2])

1.39 μs ± 148 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [12]:
%%timeit -n 10000
np_kov([1,1,3], [0,2,2])

18.7 μs ± 502 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [13]:
%%timeit -n 10000
kov_mat([1,1,3], [0,2,2])

6.92 μs ± 861 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [14]:
%%timeit -n 10000
np_kov_mat([1,1,3], [0,2,2])

91.2 μs ± 4.74 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [15]:
%%timeit -n 10000
np.cov([1,1,3], [0,2,2])

35.4 μs ± 3.97 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [16]:
rng = np.random.default_rng()

In [17]:
zfl_1 = rng.integers(-100, 100, 10_000_000).tolist()
zfl_2 = rng.integers(-100, 100, 10_000_000).tolist()
zfl_3 = rng.integers(-100, 100, 10_000_000).tolist()

In [18]:
kov_mat(zfl_1, zfl_2, zfl_3) # 10.5s

[[3331.83, 1.68, 1.39], [1.68, 3334.73, 1.56], [1.39, 1.56, 3334.52]]

In [19]:
zfl_1 = rng.integers(-100, 100, 10_000_000)
zfl_2 = rng.integers(-100, 100, 10_000_000)
zfl_3 = rng.integers(-100, 100, 10_000_000)

In [20]:
np_kov_mat(zfl_1, zfl_2, zfl_3) # 1.0s

array([[ 3.3340358e+03,  2.7920000e-01, -5.2120000e-01],
       [ 2.7920000e-01,  3.3333170e+03, -6.3170000e-01],
       [-5.2120000e-01, -6.3170000e-01,  3.3328582e+03]])

In [21]:
np.cov(np.array((zfl_1, zfl_2, zfl_3)), bias=True) # 0.3s

array([[ 3.33403584e+03,  2.79161855e-01, -5.21153387e-01],
       [ 2.79161855e-01,  3.33331697e+03, -6.31672116e-01],
       [-5.21153387e-01, -6.31672116e-01,  3.33285816e+03]])

In [23]:
np_kov(zfl_1, zfl_2)

np.float64(1.2063)

In [24]:
np.cov((zfl_1, zfl_2))

array([[3.33376061e+03, 1.20625228e+00],
       [1.20625228e+00, 3.33241613e+03]])